version: '3'
services:
  db:
    image: postgres:15
    container_name: platform-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=platform-postgresql
    ports:
      - '5432:5432'
      # - '5432:5533'
    volumes: 
      - $PWD/db:/var/lib/postgresql/data
      # - $PWD/tmp:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: platform-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - $PWD/minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data


volumes:
  db:
    driver: local
  minio_storage: {}